### ISSUE TITLE
The ploting in the example shown in the readme fails. 

### ISSUE THREAD

**Issue by BaptisteLamic** [WaveProp/HMatrices.jl#18]
Hi,  running the following block of code return an error.
```julia
using HMatrices, LinearAlgebra, StaticArrays
const Point3D = SVector{3,Float64}
# sample some points on a sphere
m = 10_000
X = Y = [Point3D(sin(θ)cos(ϕ),sin(θ)*sin(ϕ),cos(θ)) for (θ,ϕ) in zip(π*rand(m),2π*rand(m))]
function G(x,y) 
  d = norm(x-y) + 1e-8
  1/(4π*d)
end
K = KernelMatrix(G,X,Y)
H = assemble_hmat(K;atol=1e-6)
using Plots
plot(H)
```
The returned error is :
```julia
UndefVarError: Leaves not defined
```

**Comment by maltezfaria** [comment]
Can you confirm if you have the same problem on `main`? The bug should have been fixed with da9f659. I will tag a new version soon

**Comment by BaptisteLamic** [comment]
I was running the code with the last tagged version. 
It works fine on main.

**Comment by maltezfaria** [comment]
I just tagged a new version with some other minor changes. Closing this.
