### ISSUE TITLE
Support complex matrices 

### ISSUE THREAD

**Issue by KapilKhanal** [WaveProp/HMatrices.jl#45]
`evaluate_greens_func` evaluates to complex number. I get error that it is not supported."MethodError: no method matching assemble_hmat(::Vector{ComplexF64}; threads=false)"
`using HMatrices, LinearAlgebra, StaticArrays
const Point3D = SVector{3,Float64}
X = rand(Point3D,10_000)
Y = rand(Point3D,10_000)
GF,GF1,GF2,GF3 = KernelMatrix(evaluate_greens_func,X,Y)

Xclt = Yclt = ClusterTree(X)
adm = StrongAdmissibilityStd()
comp = PartialACA(;atol=1e-6)
H = assemble_hmat(GF,threads = false)`

**Comment by maltezfaria** [comment]
I am not sure what your `evaluate_greens_func` do, but one problem could be that calling 

```julia
GF,GF1,GF2,GF3 = KernelMatrix(evaluate_greens_func,X,Y)
```

will assign to `GF, GF1, GF2, GF3` the first four *elements* of the `KernelMatrix` (which is itself an `AbstractMatrix`). After that call, I suspect these four quantities are simply complex numbers. Here is an example that should work on the `v0.2.2`

```julia
using HMatrices, LinearAlgebra, StaticArrays
const Point3D = SVector{3,Float64}

X = rand(Point3D,10_000)
Y = rand(Point3D,10_000)

function evaluate_greens_func(x,y)
    d = norm(x-y) + 1e-8
    exp(im*d) / d
end

GF = KernelMatrix(evaluate_greens_func,X,Y)

Xclt = Yclt = ClusterTree(X)
adm = StrongAdmissibilityStd()
comp = PartialACA(;atol=1e-6)
H = assemble_hmatrix(GF,threads = false)

```

**Comment by maltezfaria** [comment]
@KapilKhanal Did you manage to make it work? Can I close this issue?

The library does provide support for complex matrices (I used it frequently to compress integral operators for Helmholtz equations).
