### ISSUE TITLE
Creating a `KernelMatrix` with custom row & column elements

### ISSUE THREAD

**Issue by tpgillam** [WaveProp/HMatrices.jl#53]
In [Kernel matrices documentation](https://waveprop.github.io/HMatrices.jl/stable/kernelmatrix/#kernelmatrix-section) it's stated that elements can be of any type:

> The row and columns elements may be as simple as points in $\mathbb{R}^d$ (as is the case for Nyström methods), but they can also be more complex objects such as triangles or basis functions –- the only thing required is that `f(X[i],Y[j])` make sense. 

However, I run into problems constructing `ClusterTree`s if I try to exercise this ability. Some assorted observations:

- as suggested in WavePropBase, I've implemented `HMatrices.center(::MyType)::SVector{3,Float64}`

- in the [documentation](https://waveprop.github.io/HMatrices.jl/stable/#assemble-generic-subsection), it's stated that `ClusterTree` comes from `WavePropBase`, but actually it seems this is [no longer true](https://github.com/WaveProp/HMatrices.jl/pull/27).

- whilst `WavePropBase`'s ClusterTree supports arbitrary element types, the current version in `HMatrices` [only supports SVectors](https://github.com/WaveProp/HMatrices.jl/blob/main/src/clustertree.jl#L18).

- Trying to use `WavePropBase.ClusterTree` explicitly results in a MethodError for `isleaf`.

Am I approaching this case incorrectly? Or is this a bug? In any case, I'm looking forward to using HMatrices, as it should be directly applicable to my problem if it can handle this case.
Thanks!

**Comment by maltezfaria** [comment]
This is certainly a bug. As you correctly pointed out, this package became independent of `WavePropBase` at some point, and I was not sufficiently careful to test the changes thoroughly. And the documentation is certainly outdated in the places you mentioned! 

Let me take a look at these issues, and I will get back to you soon with more information.

**Comment by maltezfaria** [comment]
If you have a MWE of what you are trying to achieve, that would be quite helpful in understanding/fixing the problem! Thanks.

**Comment by maltezfaria** [comment]
I made some small changes [here](https://github.com/WaveProp/HMatrices.jl/commit/299782e61d49aabf0ba9143edf551768237067ae) and added a simple example to `kernelmatrix.md` of how you may achieve something similar to what you asked. Let me know if this is not it :-)

**Comment by tpgillam** [comment]
> If you have a MWE

Here's a very minimal MWE. (In my case the type actually represents a some geometry of finite extent, and the kernel is a function of a pair of elements, in case that were to change anything)

```julia
using HMatrices
using StaticArrays

struct MyType
    a::Float64
    b::Float64
end

HMatrices.center(t::MyType) = (t.a + t.b) / 2

X = [MyType(x, 2 * x) for x in 1:10]
Y = X

f(x::MyType, y::MyType) = SVector(x, y)

K = KernelMatrix(f, X, Y)
assemble_hmatrix(K)
```

which gives
```
ERROR: LoadError: MethodError: no method matching ClusterTree(::Vector{MyType}, ::HyperRectangle{1, Float64}, ::UnitRange{Int64}, ::Vector{Int64}, ::Vector{Int64}, ::Nothing, ::Nothing)

Closest candidates are:
  ClusterTree(::Array{SVector{N, T}, 1}, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any) where {N, T}
   @ HMatrices ~/.julia/packages/HMatrices/prQKn/src/clustertree.jl:25
  ClusterTree(::Any, ::Any; copy_elements, threads)
   @ HMatrices ~/.julia/packages/HMatrices/prQKn/src/clustertree.jl:123
  ClusterTree(::Any; ...)
   @ HMatrices ~/.julia/packages/HMatrices/prQKn/src/clustertree.jl:123
```
```

**Comment by tpgillam** [comment]
Ahh sorry, I just saw the `map(center, ...)` that you added when moving the function. Won't test it right now but I suspect that should do the trick.

**Comment by maltezfaria** [comment]
Thanks for the MWE. I just tested it, and it runs on the `dev` branch. I will probably get this merged today, together with some other small changes I want to add, and tag a minor version. Let me know if that does not fix your issues.

For reference, it was indeed the commit simplifying the `ClusterTree` structure that broke the functionality you wanted!
